### ISSUE TITLE
Change url for maps in mentions mail

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/interpretation-app#31]
Url should change from mapping to maps. See https://github.com/dhis2/dhis2-core/pull/2019/files#diff-12fe023f400f7c4d6bf945260269b5d7R346

Target version 29, 30 and master

**Comment by tokland** [comment]
This was already fixed upstream for branches v30, v31 and master (this feature is not v29, so nothing to to there):

https://github.com/dhis2/dhis2-core/pull/2126

I fixed also for dhis2-newsletter:

https://github.com/EyeSeeTea/dhis2-newsletter/pull/13
